### PR TITLE
Added new Skybox

### PR DESCRIPTION
**Pull request by JusterGames**
Added new Skybox pack to the project and chose one that i liked.

### CODE REVIEW

**Comment by JusterGames** [comment]
This PR adds issue #9.

**Comment by brianisbrilliant** [comment]
That is A LOT of new skyboxes - please just include one skybox, and not the entire package.

This PR will be accepted when all extra files are deleted.

**Review by JusterGames — COMMENTED** [review]
Fixed the Skybox pack issue

**Comment by brianisbrilliant** [comment]
Great work getting those other files removed and getting this all sorted out.

**Pull request merged**
